baseURL = "https://rodrigocmoreira.github.io/"
languageCode = "en-us"
title = "#dev"
theme = "minimal"
disqusShortname = "rodrigocmoreira.github.io" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Rodrigo Cardoso Moreira"
    description = "Personal blog with insights, and tips of what works for me as a dev"
    githubUsername = "rodrigocmoreira"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["c#", "javascript", "Node.js", ".net", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rcardoso.moreira@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rodrigocmoreira/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/rodrigocardosomoreira/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/urodrigocardoso/"
    name = "twitter"
    weight = 4
